//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebThoiTrang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public string MAHOADON { get; set; }
        public string MAKH { get; set; }
        public string MAGIOHANG { get; set; }
        public int GIATHANHTOAN { get; set; }
        public System.DateTime NGAYTHANHTOAN { get; set; }
        public int Phone { get; set; }
        public string Address { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Id { get; set; }
    }
}
