//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebThoiTrang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAPHANKHOI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHAPHANKHOI()
        {
            this.LOHANGs = new HashSet<LOHANG>();
        }
    
        public string MANPP { get; set; }
        public string QUAN { get; set; }
        public string DUONG { get; set; }
        public string THANHPHO { get; set; }
        public string SONHA { get; set; }
        public string EMAIL { get; set; }
        public string SDT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOHANG> LOHANGs { get; set; }
    }
}
