//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebThoiTrang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatu
    {
        public string MATT { get; set; }
        public string MAHD { get; set; }
        public string TRANGTHAI { get; set; }
        public string MANVTHEODOI { get; set; }
    }
}
